.\"#ident "%W% %G%"
.\"
.\" # Copyright (C) 1994 Kubota Graphics Corp.
.\" # 
.\" # Permission to use, copy, modify, and distribute this material for
.\" # any purpose and without fee is hereby granted, provided that the
.\" # above copyright notice and this permission notice appear in all
.\" # copies, and that the name of Kubota Graphics not be used in
.\" # advertising or publicity pertaining to this material.  Kubota
.\" # Graphics Corporation MAKES NO REPRESENTATIONS ABOUT THE ACCURACY
.\" # OR SUITABILITY OF THIS MATERIAL FOR ANY PURPOSE.  IT IS PROVIDED
.\" # "AS IS", WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING THE
.\" # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" # PURPOSE AND KUBOTA GRAPHICS CORPORATION DISCLAIMS ALL WARRANTIES,
.\" # EXPRESS OR IMPLIED.
.\"
.TH DsInqNumDrivers 3D "Dore"
.SH NAME
DsInqNumDrivers \- Return the number of installed device drivers
.SH SYNOPSIS
.nf
.ft 3
C:
.in  +.5i
DtInt DsInqNumDrivers()
.sp
.in  -.5i
FORTRAN:
.in  +.5i
INTEGER *4 DSQND()
.in  -.5i
.fi 
.IX "DsInqNumDrivers"
.IX "DSQND"
.SH DESCRIPTION
.LP
\f2DsInqNumDrivers\fP returns the number of available device drivers in
the current Dore system. 
\f2DsInqNumDrivers\fP can be used in conjunction with
\f2DsInqDriverInfo\fP <\f2DSQDI\fP> to obtain a list of available
device drivers.
.SH SEE ALSO
.na
DsInqDriverInfo(3D)
.ad
