setenv DORE_LOC /nfs/palm/u/sqae/dore 
setenv DORE_OBJTYPE kgl
setenv DORE_LIB_NAME libkgl.a
#setenv CFLAGS "-g -DDORE_REAL_SINGLE -DDORE_VERSION -D_DEBUG_KOPENGL_ -DPRINT_GL" 
#setenv CFLAGS "-g -DDORE_REAL_SINGLE -DDORE_VERSION -DNO_BUFFERED_EXTENSIONS -D_DEBUG_KOPENGL_" 
setenv CFLAGS "-g -DDORE_REAL_SINGLE -DDORE_VERSION -DDENALI -DNO_BUFFERED_EXTENSIONS" 
setenv LDFLAGS "-r -g"
setenv ARFLAGS rv
